USE [master]
GO

/****** Object:  Database [Intergration]    Script Date: 1/1/2025 7:28:46 PM ******/
CREATE DATABASE [Intergration]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Intergration', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Intergration.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Intergration_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Intergration_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Intergration].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Intergration] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Intergration] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Intergration] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Intergration] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Intergration] SET ARITHABORT OFF 
GO

ALTER DATABASE [Intergration] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Intergration] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Intergration] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Intergration] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Intergration] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Intergration] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Intergration] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Intergration] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Intergration] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Intergration] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Intergration] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Intergration] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Intergration] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Intergration] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Intergration] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Intergration] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Intergration] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Intergration] SET RECOVERY FULL 
GO

ALTER DATABASE [Intergration] SET  MULTI_USER 
GO

ALTER DATABASE [Intergration] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Intergration] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Intergration] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Intergration] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Intergration] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Intergration] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Intergration] SET QUERY_STORE = ON
GO

ALTER DATABASE [Intergration] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Intergration] SET  READ_WRITE 
GO


